namespace SourceSharp.SP.Public.Engine;

public enum HTTPStatus
{
    HTTP_INVALID = -1,
    HTTP_CONNECTING = 0,
    HTTP_FETCH,
    HTTP_DONE,
    HTTP_ABORTED,
    HTTP_ERROR
}

public enum HTTPError
{
    HTTP_ERROR_NONE = 0,
    HTTP_ERROR_ZERO_LENGTH_FILE,
    HTTP_ERROR_CONNECTION_CLOSED,
    HTTP_ERROR_INVALID_URL,
    HTTP_ERROR_INVALID_PROTOCOL,
    HTTP_ERROR_CANT_BIND_SOCKET,
    HTTP_ERROR_CANT_CONNECT,
    HTTP_ERROR_NO_HEADERS,
    HTTP_ERROR_FILE_NONEXISTENT,
    HTTP_ERROR_MAX
}